### ISSUE TITLE
Sync without options throws statusCode not defined error

### ISSUE THREAD

**Issue by obimod** [lookout/gringotts#1]
Model instance sync call without an options dict, like the following
```
@model.sync('update', @response)
```
throws the error in the browser:
```
Uncaught TypeError: Cannot read property 'statusCode' of undefined
```

**Comment by naganowl** [comment]
Closed in https://github.com/lookout/gringotts/commit/131baadc1bb3d324a29a9e29bffedeb1ec6b1b2d
