### ISSUE TITLE
Add in Base MVC

### ISSUE THREAD

**Issue by obimod** [lookout/gringotts#12]
We need to add our base MVC classes into Gringotts.
```
models/base/model
models/base/collection
models/base/paginated-collection
views/base/view
views/base/collection-view
views/base/paginated-view
views/base/modal-view
controllers/base/controller
```

**Comment by eugenet8k** [comment]
Maybe not all of them. For now Model and Collection were introduced into gringotts within #25. We definitely need ModalView and Pagination-related classes there too. I am still thinking on Controller + Notifications. It seems they may be introduced to gringotts as well.

**Comment by obimod** [comment]
Cutting this ticket up into smaller ones... i.e. #28
