### ISSUE TITLE
Delete advice.coffee and move into base model/view

### ISSUE THREAD

**Issue by obimod** [lookout/gringotts#13]
Advice.coffee just implemented Twitter's advice. We should move this extension into the base model and the base view and delete advice.coffee.

**Comment by eugenet8k** [comment]
I am slowly working on this. I think there are around dozen mixins that need to be updated to not use AOP.

**Comment by eugenet8k** [comment]
This was fixed as part of https://github.com/lookout/gringotts/commit/93d536cdb98d380d68964f0aae0b551b610089b2 commit/
