### ISSUE TITLE
Combine bad-model into a more generic error mixin

### ISSUE THREAD

**Issue by obimod** [lookout/gringotts#14]
bad-model.coffee
* delete & combine into another module (error-gate perhaps?)
* does notifications based on the return resp.statusCode
* remove the redirect
* provide instructions for extending the error handling

**Comment by egeste** [comment]
I like what I'm seeing in this repo. Keep up the good work.

**Comment by eugenet8k** [comment]
We still need bad-model, in some places this is a useful way to quickly handle ajax error with special behavior like navigating to previous page. The only thing I add is that models that are handled by bad-model will mark xhr as handled so the generic errors handler will not show duplicated message for an error.

**Comment by obimod** [comment]
We're literally changing the composition of all backbone models which mixin this functionality by overriding the method, applying behavior before, and then executing it. I would expect this to create an entire extra layer of call stacks within the model's constructor. 

I propose that we move this to the base model and call it in a normal fashion and delete the mixin after #12 is completed to eliminate this messing around with the framework's constructor call stack.
