### ISSUE TITLE
editable.coffee

### ISSUE THREAD

**Issue by obimod** [lookout/gringotts#17]
This should probably be a component within a larger form component. Right now it's one-off and sprinkled within views.

Further analysis required
* follow up item: uses document.execCommand which has questionable support
* saveMessage option passed in which is then passed into delayedSave mixin further coupling the two
* should not assume that the value of these are numbers. convertNumber is called for all returned values.
* not clear that the success handler needs implemented for anything to happen. Also not clear what that implementation should look like.

**Comment by eugenet8k** [comment]
I think it works just fine now. Now with genericSave we can decide if we want to delay save or not.

**Comment by obimod** [comment]
Closing per recent commits.
