### ISSUE TITLE
Mixin string-template has a hardcoded template path 

### ISSUE THREAD

**Issue by eugenet8k** [lookout/gringotts#19]
There is a possibility to override it by passing `templatePath` in options. But if we consider (and we do) using template in hundreds of views, having this settings in every view is painful. 

There should be a way to configure default template path using a global config or other one-time definition per app context.

**Comment by obimod** [comment]
:+1:

**Comment by eugenet8k** [comment]
Well, it seems that the current implementation is best of possible. If there is a need of using custom tempalatePath then consider placing this mixing in the base class for all views and set up custom path there:

```coffeescript
  class View extends Chaplin.View
    stringTemplate.call @prototype, templatePath: 'templates'
```
