### ISSUE TITLE
combine service-unavailable with error-gate (formerly bad-model)

### ISSUE THREAD

**Issue by obimod** [lookout/gringotts#21]
service-unavailable.coffee
* Next steps: Combine with error-gate
* duplicating bad-model
* requires Chaplin SyncMachine

**Comment by eugenet8k** [comment]
Service-unavailable was refactored and all error-handling logic was extracted into generic ajax errors handling.

**Comment by obimod** [comment]
Seems that backbone has a onError handler which calls defaultOnError and suggests using this method to standardize request error handling [1]. I think we should leverage Backbone and remove as much error sprinkles as possible. They don't leave a good taste in my mouth.. 

[1] https://github.com/jashkenas/backbone/blob/979adf5200794ff33a45498f5be6cb07a1f45624/test/vendor/require.js#L1791

**Comment by obimod** [comment]
Reopened the discussion... perhaps we can remove all error handling and better integrate with Backbone?

**Comment by obimod** [comment]
Oh shoot.. just realized that the onError method is dealing with requireJS and not remote ajax handling... closing for now.
