### ISSUE TITLE
Delete notification.coffee

### ISSUE THREAD

**Issue by obimod** [lookout/gringotts#22]
notification.coffee
* Next step: delete
* Shouldn't be a client feature since the action wouldn't be able to persist upon browser exit
* We should use @publishEvent for talking with the user
* Not currently being implemented via opts: {undo: true}

Purpose: Allows the user to undo an action by deferring the server request

Risks:
* Maybe user exits browser before the request is sent

Potential solution: ask the user if there is still a request in progress if the user wants to leave

**Comment by eugenet8k** [comment]
I think we just need to kill a mixin and introduce NotificationView into gringotts.
