### ISSUE TITLE
consolidating the error handling mixins

### ISSUE THREAD

**Issue by obimod** [lookout/gringotts#3]
There exists three mixin' which deal with form error handling. This ticket is to discovery and implement converting them into one single mixin'. Default model and collection error handling within Backbone should make this possible.

**Comment by obimod** [comment]
Documenting these mixins to contribute to the JSDoc issue #4 as well as to help solve this issue.

**Comment by eugenet8k** [comment]
Mixins consolidated as much as possible into a generic errors handling hood to all ajax errors.
