### ISSUE TITLE
Any documentation or sample project ?

### ISSUE THREAD

**Issue by jm-pro** [lookout/gringotts#78]
http://hackers.lookout.com/gringotts/  is not working any more
and archive.org has no copy.

Is there any documentation available ?

**Comment by eugenet8k** [comment]
@jm-pro thanks for your interest to this repo. At this point, the documentation is available only in form of comments within CoffeeScript modules. Please let us know what's your possible application for this library and maybe we will be able to suggest or prepare for you better documentation.
